src/main/java/com/sparta/ddang/config/SecurityConfig.java
src/main/java/com/sparta/ddang/domain/member/controller/MemberController.java
src/main/java/com/sparta/ddang/domain/member/dto/MemberRequestDto.java
src/main/java/com/sparta/ddang/domain/member/dto/MemberResponseDto.java
src/main/java/com/sparta/ddang/domain/member/entity/Member.java
src/main/java/com/sparta/ddang/domain/member/repository/MemberRepository.java
src/main/java/com/sparta/ddang/domain/member/service/MemberDetailsServcie.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

민준님과 회원가입과 로그인 구현 #3

---

src/main/java/com/sparta/ddang/config/SecurityConfig.java
src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/repository/AuctionRepository.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/category/dto/CategoryResponseDto.java
src/main/java/com/sparta/ddang/domain/category/entity/Category.java
src/main/java/com/sparta/ddang/domain/category/repository/CategoryRepository.java
src/main/java/com/sparta/ddang/domain/favorite/dto/FavoriteResponseDto.java
src/main/java/com/sparta/ddang/domain/favorite/entity/Favorite.java
src/main/java/com/sparta/ddang/domain/favorite/repository/FavoriteRespository.java
src/main/java/com/sparta/ddang/domain/member/controller/MemberController.java
src/main/java/com/sparta/ddang/domain/member/dto/request/EmailRequestDto.java
src/main/java/com/sparta/ddang/domain/member/dto/request/LoginRequestDto.java
src/main/java/com/sparta/ddang/domain/member/dto/request/NicknameRequestDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MemberRequestDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MemberResponseDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MypageResponseDto.java
src/main/java/com/sparta/ddang/domain/member/entity/Member.java
src/main/java/com/sparta/ddang/domain/member/repository/MemberRepository.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/domain/participant/entity/Participant.java
src/main/java/com/sparta/ddang/domain/participant/repository/ParticipantRepository.java
src/main/java/com/sparta/ddang/domain/region/dto/RegionResponseDto.java
src/main/java/com/sparta/ddang/domain/region/entity/Region.java
src/main/java/com/sparta/ddang/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/ddang/domain/viewcnt/entity/ViewCnt.java
src/main/java/com/sparta/ddang/domain/viewcnt/repository/ViewCntRepository.java
src/main/java/com/sparta/ddang/util/Timestamped.java

나머지 P0기능 완료 #10, #11, #12, #19, #20, #21, #22, #23, #24, #25, #26, #27, #28, #29, #30

나머지 P0기능 완료 #10, #11, #12, #19, #20, #21, #22, #23, #24, #25, #26, #27, #28, #29, #30

---

src/main/java/com/sparta/ddang/domain/member/controller/MemberController.java
src/main/java/com/sparta/ddang/domain/member/dto/response/KakaoUserInfoDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MemberResponseDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MypageResponseDto.java
src/main/java/com/sparta/ddang/domain/member/entity/Member.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/jwt/TokenProvider.java

phoneNumber 삭제 및 카카오 연동로그인 로직 구현 그러나 프런트와 확인 전

phoneNumber 삭제 및 카카오 연동로그인 로직 구현 그러나 프런트와 확인 전

---

src/main/java/com/sparta/ddang/domain/member/controller/MemberController.java
src/main/java/com/sparta/ddang/domain/member/dto/response/KakaoUserInfoDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MypageResponseDto.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

카카오 로그인 구현

---

src/main/java/com/sparta/ddang/domain/member/dto/response/KakaoLoginResponseDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/KakaoUserInfoDto.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

카카오 로그인 최종 구현

---

build.gradle
src/main/java/com/sparta/ddang/config/SecurityConfig.java
src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/request/AuctionTagsRequestDto.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionTagsResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/repository/AuctionRepository.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/domain/tag/entity/Tags.java
src/main/java/com/sparta/ddang/domain/tag/repository/TagsRepository.java

카카오 소셜 로그인 #18, 경매 검색 #35, 태그 기능 #36

카카오 소셜 로그인 #18, 경매 검색 #35, 태그 기능 #36

---

src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionIdResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/repository/AuctionRepository.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/favorite/repository/FavoriteRespository.java
src/main/java/com/sparta/ddang/domain/mulltiimg/entity/MultiImage.java
src/main/java/com/sparta/ddang/domain/pagination/controller/PagingController.java
src/main/java/com/sparta/ddang/domain/pagination/service/PagingService.java
src/main/java/com/sparta/ddang/domain/participant/repository/ParticipantRepository.java

페이징 기능 구현 #38

---

src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/category/dto/CategoryOnlyResponseDto.java
src/main/java/com/sparta/ddang/domain/category/repository/CategoryRepository.java
src/main/java/com/sparta/ddang/domain/member/controller/MemberController.java
src/main/java/com/sparta/ddang/domain/member/dto/response/KakaoLoginResponseDto.java
src/main/java/com/sparta/ddang/domain/member/dto/response/MypageResponseDto.java
src/main/java/com/sparta/ddang/domain/member/entity/Member.java
src/main/java/com/sparta/ddang/domain/member/repository/MemberRepository.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/domain/region/dto/RegionOnlyResponseDto.java
src/main/java/com/sparta/ddang/domain/region/entity/Region.java
src/main/java/com/sparta/ddang/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/ddang/domain/tag/entity/Tags.java

다른 회원 정보 조회 #40 , 카테고리 및 지역 목록 오름차순으로 response하기 #41

다른 회원 정보 조회 #40 , 카테고리 및 지역 목록 오름차순으로 response하기 #41

---

src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/repository/AuctionRepository.java
src/main/java/com/sparta/ddang/domain/favorite/repository/FavoriteRespository.java
src/main/java/com/sparta/ddang/domain/member/dto/response/GetMypageResponseDto.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/domain/viewcnt/entity/ViewCnt.java

마이페이지 조회시 내가 생성한경매 게시글 수, 내가 참여한 경매 수, 내가 관심있는 경매 수 #44

마이페이지 조회시 내가 생성한경매 게시글 수, 내가 참여한 경매 수, 내가 관심있는 경매 수 #44

---

src/main/java/com/sparta/ddang/domain/chat/controller/ChatRoomController.java
src/main/java/com/sparta/ddang/domain/chat/controller/MessageController.java
src/main/java/com/sparta/ddang/domain/chat/entity/ChatMessage.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java

깃 충돌일어나서 다시 커밋

---

src/main/java/com/sparta/ddang/domain/member/entity/Member.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

비밀번호 확인 기능 보완, 경매게시글 response 변경

비밀번호 확인 기능 보완, 경매게시글 response 변경

---

src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionChatResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

경매 생성시 경매 채팅방 생성 #59, 상세 페이지 접근시 경매 채팅방 roomId반환 #60

경매 생성시 경매 채팅방 생성 #59, 상세 페이지 접근시 경매 채팅방 roomId반환 #60

---

src/main/java/com/sparta/ddang/config/SecurityConfig.java
src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionRankResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/repository/AuctionRepository.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/controller/MessageController.java
src/main/java/com/sparta/ddang/domain/chat/dto/ChatMessageDto.java
src/main/java/com/sparta/ddang/domain/chat/entity/ChatMessage.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java
src/main/java/com/sparta/ddang/domain/member/repository/MemberRepository.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

경매 인기 top4 조회 #63, 경매 채팅메시지 시간, 닉네임, 프로필이미지 반환 #64

경매 인기 top4 조회 #63, 경매 채팅메시지 시간, 닉네임, 프로필이미지 반환 #64

---

src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionRankResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/controller/ChatRoomController.java
src/main/java/com/sparta/ddang/domain/chat/dto/ChatMessageDto.java
src/main/java/com/sparta/ddang/domain/chat/dto/OnoChatMessageDto.java
src/main/java/com/sparta/ddang/domain/chat/entity/ChatMessage.java
src/main/java/com/sparta/ddang/domain/chat/entity/OnoChatMessage.java
src/main/java/com/sparta/ddang/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/sparta/ddang/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/sparta/ddang/domain/chat/repository/OnoChatMessageRepository.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java

해당 회원의 1:1 채팅 목록 조회. (부분 완성)  #70

해당 회원의 1:1 채팅 목록 조회. (부분 완성)  #70

---

src/main/java/com/sparta/ddang/util/Timestamped.java

fix : Timestamped @setter 추가

---

build.gradle
src/main/java/com/sparta/ddang/config/SecurityConfig.java
src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/favorite/dto/FavoriteResponseDto.java
src/main/java/com/sparta/ddang/domain/notification/Listener/NotificationListener.java
src/main/java/com/sparta/ddang/domain/notification/controller/NotificationController.java
src/main/java/com/sparta/ddang/domain/notification/dto/NotificationRequestDto.java
src/main/java/com/sparta/ddang/domain/notification/dto/NotificationResponseDto.java
src/main/java/com/sparta/ddang/domain/notification/entity/Notification.java
src/main/java/com/sparta/ddang/domain/notification/entity/NotificationContent.java
src/main/java/com/sparta/ddang/domain/notification/entity/NotificationType.java
src/main/java/com/sparta/ddang/domain/notification/repository/EmitterRepository.java
src/main/java/com/sparta/ddang/domain/notification/repository/EmitterRepositoryImpl.java
src/main/java/com/sparta/ddang/domain/notification/repository/NotificationRepository.java
src/main/java/com/sparta/ddang/domain/notification/service/NotificationService.java

fix: FavoriteResponseDto auctionId 오타 수정

feat: 실시간 알림 기능 구현 중 #99

---

src/main/java/com/sparta/ddang/domain/auction/controller/AuctionController.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/DoneAuctionResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/controller/ChatRoomController.java
src/main/java/com/sparta/ddang/domain/chat/controller/MessageController.java

fix: 경매 테이블 컬럼 추가 (auctionDone, reviewDone), 관련 api 수정
fix: 인기경매(top4) 조회시 진행중인 경매만 조회되게 수정

feat: 경매 종료(거래 종료) 기능 구현 완료

---

src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

프로필 수정 이미지 해결 #107

---

src/main/java/com/sparta/ddang/domain/chat/repository/OnoChatMessageRepository.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java

fix : 1:1 채팅 마지막 메시지 입력한 것만 response하기(#111 )

fix : 1:1 채팅 마지막 메시지 입력한 것만 response하기(#111 )

---

src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionDetailResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java
src/main/java/com/sparta/ddang/domain/notification/controller/NotificationController.java

fix : 1:1 채팅방 입장한 사람 수 카운트(#113),  실시간 입찰시 입장이 안되는 문제 해결 (#114)

fix : 1:1 채팅방 입장한 사람 수 카운트(#113),  실시간 입찰시 입장이 안되는 문제 해결 (#114)

---

src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/chat/service/ChatService.java

fix : paritcipant가 중복 저장되는 오류 수정(#118)

fix : paritcipant가 중복 저장되는 오류 수정(#118)

---

src/main/java/com/sparta/ddang/domain/auction/dto/resposne/AuctionDetailResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/dto/resposne/DoneAuctionResponseDto.java
src/main/java/com/sparta/ddang/domain/auction/entity/Auction.java
src/main/java/com/sparta/ddang/domain/auction/service/AuctionService.java
src/main/java/com/sparta/ddang/domain/member/service/MemberService.java

fix: 경매 상세 조회 시 신뢰도 등급 반환 추가
fix: 신뢰도 등급 영어에서 한글로 변경

fix: auctionDone -> sellerDone, bidderDone
